services:

  backend:
    build:
      context: ./backend
    container_name: inventory-backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://inventory_app:Test1234@postgres:5432/inventory
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
    container_name: inventory-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
  postgres:
    image: postgres:15-alpine
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory_app
      POSTGRES_PASSWORD: Test1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:Z
volumes:
  postgres_data:
